/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.management.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author METROPOLITAN
 */
public class AddRooms extends javax.swing.JFrame {

    /**
     * Creates new form AddRooms
     */
    public AddRooms() {
        initComponents();
        setTitle("Add Rooms");
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelImage = new javax.swing.JLabel();
        LabelAddRooms = new javax.swing.JLabel();
        LabelRoomNumber = new javax.swing.JLabel();
        LabelAvailability = new javax.swing.JLabel();
        LabelCleaningStatus = new javax.swing.JLabel();
        LabelPrice = new javax.swing.JLabel();
        LabelRoomType = new javax.swing.JLabel();
        TextField1 = new javax.swing.JTextField();
        ComboBoxAvailability = new javax.swing.JComboBox<>();
        ComboBoxCleaningStatus = new javax.swing.JComboBox<>();
        TextField2 = new javax.swing.JTextField();
        ComboBoxRoomType = new javax.swing.JComboBox<>();
        ButtonBack = new javax.swing.JButton();
        ButtonClear = new javax.swing.JButton();
        ButtonAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        LabelImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\METROPOLITAN\\Desktop\\Icons\\twelvenew.jpg")); // NOI18N

        LabelAddRooms.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LabelAddRooms.setForeground(new java.awt.Color(255, 102, 0));
        LabelAddRooms.setText("Add Rooms");

        LabelRoomNumber.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        LabelRoomNumber.setText("Room Number");

        LabelAvailability.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        LabelAvailability.setText("Availability");

        LabelCleaningStatus.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        LabelCleaningStatus.setText("Cleaning Status");

        LabelPrice.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        LabelPrice.setText("Price");

        LabelRoomType.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        LabelRoomType.setText("Room Type");

        TextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        ComboBoxAvailability.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ComboBoxAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxAvailabilityActionPerformed(evt);
            }
        });

        ComboBoxCleaningStatus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        TextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        ComboBoxRoomType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        ButtonBack.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ButtonBack.setText("Back");
        ButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackActionPerformed(evt);
            }
        });

        ButtonClear.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ButtonClear.setText("Clear");
        ButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClearActionPerformed(evt);
            }
        });

        ButtonAdd.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ButtonAdd.setText("Add");
        ButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(LabelAddRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(LabelRoomNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelAvailability, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelCleaningStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LabelPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextField1)
                            .addComponent(ComboBoxAvailability, 0, 250, Short.MAX_VALUE)
                            .addComponent(ComboBoxCleaningStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ComboBoxRoomType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextField2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ButtonBack)
                        .addGap(31, 31, 31)
                        .addComponent(ButtonClear)
                        .addGap(46, 46, 46)
                        .addComponent(ButtonAdd)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(LabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelAddRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelRoomNumber)
                            .addComponent(TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelAvailability)
                            .addComponent(ComboBoxAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelCleaningStatus)
                            .addComponent(ComboBoxCleaningStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelRoomType)
                            .addComponent(ComboBoxRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelPrice)
                            .addComponent(TextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(LabelImage)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonBack)
                    .addComponent(ButtonClear)
                    .addComponent(ButtonAdd))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1018, 506));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        ComboBoxAvailability.addItem("Available");
        ComboBoxAvailability.addItem("Occupied");
        
        ComboBoxCleaningStatus.addItem("Cleaned");
        ComboBoxCleaningStatus.addItem("Dirty");
        
        ComboBoxRoomType.addItem("Standard Twin Room");
        ComboBoxRoomType.addItem("Budget Twin Room (Fan)");
        ComboBoxRoomType.addItem("Deluxe King Room (No Windows)");
        ComboBoxRoomType.addItem("Deluxe King Room (Courtyard View)");
        ComboBoxRoomType.addItem("Deluxe King Room (City View)");
        ComboBoxRoomType.addItem("Standard Queen Room (Street View)");
        ComboBoxRoomType.addItem("Deluxe Twin Room (City View)");
        ComboBoxRoomType.addItem("Budget Queen Room");
        ComboBoxRoomType.addItem("Deluxe Twin Room (Courtyard View)");
    }//GEN-LAST:event_formWindowActivated

    private void ButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonClearActionPerformed
        TextField1.setText("");
        TextField2.setText("");
        ComboBoxAvailability.setSelectedIndex(0);
        ComboBoxRoomType.setSelectedIndex(0);
        ComboBoxCleaningStatus.setSelectedIndex(0);       
    }//GEN-LAST:event_ButtonClearActionPerformed

    private void ButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackActionPerformed
        HotelManagement homa = new HotelManagement();
        homa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonBackActionPerformed

    private void ComboBoxAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxAvailabilityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxAvailabilityActionPerformed

    private void ButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddActionPerformed
        String roomNo = TextField1.getText();
        String roomAvaila = (String)ComboBoxAvailability.getSelectedItem();
        String roomClean = (String)ComboBoxCleaningStatus.getSelectedItem();
        int roomPrice = Integer.parseInt(TextField2.getText());
        String roomType = (String)ComboBoxRoomType.getSelectedItem();
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/projecthms","root","root");
            Statement stmt = (Statement)conn.createStatement();
            
            String insert = "INSERT INTO rooms" + "(Room_Number,Availability,Cleaning_Status,Price,Room_Type) VALUES"
                    + "('"+roomNo+"','"+roomAvaila+"','"+roomClean+"','"+roomPrice+"','"+roomType+"');";
            
            try {
                stmt.executeUpdate(insert);
                JOptionPane.showMessageDialog(null, "New Room Added");
                this.setVisible(true);
                
            } catch (Exception e) {
                System.out.println(e);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage() ,"Error", 1);
        }
    }//GEN-LAST:event_ButtonAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddRooms().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAdd;
    private javax.swing.JButton ButtonBack;
    private javax.swing.JButton ButtonClear;
    private javax.swing.JComboBox<String> ComboBoxAvailability;
    private javax.swing.JComboBox<String> ComboBoxCleaningStatus;
    private javax.swing.JComboBox<String> ComboBoxRoomType;
    private javax.swing.JLabel LabelAddRooms;
    private javax.swing.JLabel LabelAvailability;
    private javax.swing.JLabel LabelCleaningStatus;
    private javax.swing.JLabel LabelImage;
    private javax.swing.JLabel LabelPrice;
    private javax.swing.JLabel LabelRoomNumber;
    private javax.swing.JLabel LabelRoomType;
    private javax.swing.JTextField TextField1;
    private javax.swing.JTextField TextField2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
