/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.management.system;

/**
 *
 * @author METROPOLITAN
 */
public class HotelReception extends javax.swing.JFrame {

    /**
     * Creates new form HotelReception
     */
    public HotelReception() {
        initComponents();
        setTitle("Hotel Reception");
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelImage = new javax.swing.JLabel();
        ButtonNewCusForm = new javax.swing.JButton();
        ButtonRoom = new javax.swing.JButton();
        ButtonAllEmployeeInfo = new javax.swing.JButton();
        ButtonCustomerInfo = new javax.swing.JButton();
        ButtonCheckOut = new javax.swing.JButton();
        ButtonUpdateCheckStatus = new javax.swing.JButton();
        ButtonUpdateRoomStatus = new javax.swing.JButton();
        ButtonPickUpService = new javax.swing.JButton();
        ButtonSearchRoom = new javax.swing.JButton();
        ButtonLogOut = new javax.swing.JButton();
        ButtonBill = new javax.swing.JButton();
        ButtonBillInfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelImage.setIcon(new javax.swing.ImageIcon("D:\\Lakindu2020\\NetBeansProjects\\Hotel Management System\\src\\hotel\\management\\system\\icons\\fourth.jpg")); // NOI18N

        ButtonNewCusForm.setBackground(new java.awt.Color(0, 0, 0));
        ButtonNewCusForm.setFont(new java.awt.Font("Adobe Hebrew", 1, 16)); // NOI18N
        ButtonNewCusForm.setForeground(new java.awt.Color(255, 255, 255));
        ButtonNewCusForm.setText("New Customer Form");
        ButtonNewCusForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNewCusFormActionPerformed(evt);
            }
        });

        ButtonRoom.setBackground(new java.awt.Color(0, 0, 0));
        ButtonRoom.setFont(new java.awt.Font("Adobe Hebrew", 1, 16)); // NOI18N
        ButtonRoom.setForeground(new java.awt.Color(255, 255, 255));
        ButtonRoom.setText("Room");
        ButtonRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRoomActionPerformed(evt);
            }
        });

        ButtonAllEmployeeInfo.setBackground(new java.awt.Color(0, 0, 0));
        ButtonAllEmployeeInfo.setFont(new java.awt.Font("Adobe Hebrew", 1, 16)); // NOI18N
        ButtonAllEmployeeInfo.setForeground(new java.awt.Color(255, 255, 255));
        ButtonAllEmployeeInfo.setText("All Employee Info");
        ButtonAllEmployeeInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAllEmployeeInfoActionPerformed(evt);
            }
        });

        ButtonCustomerInfo.setBackground(new java.awt.Color(0, 0, 0));
        ButtonCustomerInfo.setFont(new java.awt.Font("Adobe Hebrew", 1, 16)); // NOI18N
        ButtonCustomerInfo.setForeground(new java.awt.Color(255, 255, 255));
        ButtonCustomerInfo.setText("Customer Info");
        ButtonCustomerInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCustomerInfoActionPerformed(evt);
            }
        });

        ButtonCheckOut.setBackground(new java.awt.Color(0, 0, 0));
        ButtonCheckOut.setFont(new java.awt.Font("Adobe Hebrew", 1, 16)); // NOI18N
        ButtonCheckOut.setForeground(new java.awt.Color(255, 255, 255));
        ButtonCheckOut.setText("Check Out");
        ButtonCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCheckOutActionPerformed(evt);
            }
        });

        ButtonUpdateCheckStatus.setBackground(new java.awt.Color(0, 0, 0));
        ButtonUpdateCheckStatus.setFont(new java.awt.Font("Adobe Hebrew", 1, 16)); // NOI18N
        ButtonUpdateCheckStatus.setForeground(new java.awt.Color(255, 255, 255));
        ButtonUpdateCheckStatus.setText("Update Check Status ");
        ButtonUpdateCheckStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonUpdateCheckStatusActionPerformed(evt);
            }
        });

        ButtonUpdateRoomStatus.setBackground(new java.awt.Color(0, 0, 0));
        ButtonUpdateRoomStatus.setFont(new java.awt.Font("Adobe Hebrew", 1, 16)); // NOI18N
        ButtonUpdateRoomStatus.setForeground(new java.awt.Color(255, 255, 255));
        ButtonUpdateRoomStatus.setText("Update Room Status");
        ButtonUpdateRoomStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonUpdateRoomStatusActionPerformed(evt);
            }
        });

        ButtonPickUpService.setBackground(new java.awt.Color(0, 0, 0));
        ButtonPickUpService.setFont(new java.awt.Font("Adobe Hebrew", 1, 16)); // NOI18N
        ButtonPickUpService.setForeground(new java.awt.Color(255, 255, 255));
        ButtonPickUpService.setText("Pick Up Service");
        ButtonPickUpService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPickUpServiceActionPerformed(evt);
            }
        });

        ButtonSearchRoom.setBackground(new java.awt.Color(0, 0, 0));
        ButtonSearchRoom.setFont(new java.awt.Font("Adobe Hebrew", 1, 16)); // NOI18N
        ButtonSearchRoom.setForeground(new java.awt.Color(255, 255, 255));
        ButtonSearchRoom.setText("Search Room");
        ButtonSearchRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSearchRoomActionPerformed(evt);
            }
        });

        ButtonLogOut.setBackground(new java.awt.Color(0, 0, 0));
        ButtonLogOut.setFont(new java.awt.Font("Adobe Hebrew", 1, 16)); // NOI18N
        ButtonLogOut.setForeground(new java.awt.Color(255, 255, 255));
        ButtonLogOut.setText("Log Out");
        ButtonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLogOutActionPerformed(evt);
            }
        });

        ButtonBill.setBackground(new java.awt.Color(0, 0, 0));
        ButtonBill.setFont(new java.awt.Font("Adobe Hebrew", 1, 16)); // NOI18N
        ButtonBill.setForeground(new java.awt.Color(255, 255, 255));
        ButtonBill.setText("Customer Bill");
        ButtonBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBillActionPerformed(evt);
            }
        });

        ButtonBillInfo.setBackground(new java.awt.Color(0, 0, 0));
        ButtonBillInfo.setFont(new java.awt.Font("Adobe Hebrew", 1, 16)); // NOI18N
        ButtonBillInfo.setForeground(new java.awt.Color(255, 255, 255));
        ButtonBillInfo.setText("Bill Info");
        ButtonBillInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBillInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ButtonBillInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonRoom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonCustomerInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonAllEmployeeInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonCheckOut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonBill, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonNewCusForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ButtonUpdateRoomStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonPickUpService, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonSearchRoom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonLogOut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonUpdateCheckStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(37, 37, 37)
                .addComponent(LabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(LabelImage))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(ButtonNewCusForm)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonRoom)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonAllEmployeeInfo)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonCustomerInfo)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonBill)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonCheckOut)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonBillInfo)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonUpdateCheckStatus)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonUpdateRoomStatus)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonPickUpService)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonSearchRoom)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonLogOut)))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(793, 687));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonNewCusFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNewCusFormActionPerformed
        NewCustomerForm cusde = new NewCustomerForm();
        cusde.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonNewCusFormActionPerformed

    private void ButtonAllEmployeeInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAllEmployeeInfoActionPerformed
        AllEmployeeInfo ali = new AllEmployeeInfo();
        ali.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonAllEmployeeInfoActionPerformed

    private void ButtonRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRoomActionPerformed
        RoomInfo ri = new RoomInfo();
        ri.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonRoomActionPerformed

    private void ButtonCustomerInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCustomerInfoActionPerformed
        CustomerInfo ci = new CustomerInfo();
        ci.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonCustomerInfoActionPerformed

    private void ButtonUpdateRoomStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonUpdateRoomStatusActionPerformed
        UpdateRoom ur = new UpdateRoom();
        ur.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonUpdateRoomStatusActionPerformed

    private void ButtonUpdateCheckStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonUpdateCheckStatusActionPerformed
        UpdateCheck uc = new UpdateCheck();
        uc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonUpdateCheckStatusActionPerformed

    private void ButtonCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCheckOutActionPerformed
        CheckOut co = new CheckOut();
        co.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonCheckOutActionPerformed

    private void ButtonSearchRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSearchRoomActionPerformed
        SearchRoom sr = new SearchRoom();
        sr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonSearchRoomActionPerformed

    private void ButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLogOutActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ButtonLogOutActionPerformed

    private void ButtonPickUpServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPickUpServiceActionPerformed
        PickupService ps = new PickupService();
        ps.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonPickUpServiceActionPerformed

    private void ButtonBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBillActionPerformed
        CustomerBill cb = new CustomerBill();
        cb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonBillActionPerformed

    private void ButtonBillInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBillInfoActionPerformed
        BillInfo bi = new BillInfo();
        bi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonBillInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HotelReception.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HotelReception.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HotelReception.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HotelReception.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HotelReception().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAllEmployeeInfo;
    private javax.swing.JButton ButtonBill;
    private javax.swing.JButton ButtonBillInfo;
    private javax.swing.JButton ButtonCheckOut;
    private javax.swing.JButton ButtonCustomerInfo;
    private javax.swing.JButton ButtonLogOut;
    private javax.swing.JButton ButtonNewCusForm;
    private javax.swing.JButton ButtonPickUpService;
    private javax.swing.JButton ButtonRoom;
    private javax.swing.JButton ButtonSearchRoom;
    private javax.swing.JButton ButtonUpdateCheckStatus;
    private javax.swing.JButton ButtonUpdateRoomStatus;
    private javax.swing.JLabel LabelImage;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
